services:
  - type: web
    name: shopfastion
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:xxxxxxx
      - key: MONGODB_DSN
        value: mongodb+srv://user:password@cluster0.mongodb.net/shopfastion?retryWrites=true&w=majority
