services:
  - type: web
    name: shopfastion
    env: php
    buildCommand: |
      apt-get update && apt-get install -y \
        pkg-config \
        libssl-dev \
        libcurl4-openssl-dev \
        && pecl install mongodb \
        && docker-php-ext-enable mongodb
    startCommand: "vendor/bin/heroku-php-apache2 public/"  # Thay bằng start command của bạn