services:
  - type: web
    name: shopfastion
    env: php
    buildCommand: |
      apt-get update && apt-get install -y \
        pkg-config \
        libssl-dev \
        libcurl4-openssl-dev \
        openssl \
        build-essential \
        && pecl install mongodb \
        && docker-php-ext-configure mongodb --with-mongodb-ssl=shared \
        && docker-php-ext-install mongodb \
        && docker-php-ext-enable mongodb \
        && composer install --no-dev --optimize-autoloader
    startCommand: "vendor/bin/heroku-php-apache2 public/"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: APP_KEY
        value: base64:1kLxxobOyim1i1yWlGn56Yf19DdsvDnNwac/I1HIygg=
      - key: DB_CONNECTION
        value: mongodb
      - key: DB_URI
        value: mongodb+srv://username:password@cluster0.mongodb.net/your_database?retryWrites=true&w=majority
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: CLOUDINARY_CLOUD_NAME
        value: your_cloud_name
      - key: CLOUDINARY_API_KEY
        value: your_api_key
      - key: CLOUDINARY_API_SECRET
        value: your_api_secret
    plan: free
    region: oregon
    branch: main